### ISSUE TITLE
Request: make D.COM show the directory without the query

### ISSUE THREAD

**Issue by rfka01** [Dietrich-L/CPM-65-for-Apple-II#7]
The D.COM directory program asks for confirmation/offers the user the opportunity the chance to change the disk before displaying the actual directory, then quits back to the prompt.
If you just want to see the directory of the current disk, this mandatory step could be annoying in the long run. In addition, if you want to go through a stack of disks that don't contain D.COM, you have to go back to the system disk to run the utility again.
A solution could be to introduce a parameter that explicitly specifies you want to view a different disk's directory, or an interactive mode like vanilla CP/M's PIP has to load the DIR utility with a bespoke prompt that you then only quit when you're done.

**Comment by Dietrich-L** [comment]
I have thougth about that an came up with this:
A>D shows the directory without query
A>D B: shows the directory without query
A>D A: shows the directory with query

Would this be satisfactory?

Dietrich

**Comment by rfka01** [comment]
If calling D without a parameter works on the currently logged in drive (as supposed to only work on A>) that would be nice.
Is the D utility providing the logging in of the disk that you have to use Ctrl-C for after a disk swap on other CP/M systems?

**Comment by Dietrich-L** [comment]
> If calling D without a parameter works on the currently logged in drive (as supposed to only work on A>) that would be nice.
Yes. A: is just an example

> Is the D utility providing the logging in of the disk that you have to use Ctrl-C for after a disk swap on other CP/M systems?
No Ctrl-C needed in CPM-65. The system always assumes, that the disc has changed. The performance penalty for this is surprisingly small, i.e. not noticable. Disc access on the Apple II is notoriously slow though….

**Comment by Dietrich-L** [comment]
New version D.COM V2.1 published
